---
title: "Week 1"
subtitle: "Quarto"
date: 2023-02-01
---

# Installation & Setup {.unnumbered}

The installation procedure will differ depending on how you choose to work with the Quarto publishing system. Below we go into the following 2 situations:

1. Using Quarto with Python or R in Visual Studio Code
2. Using Quarto with R in RStudio

It is also possible to use Quarto with Python in Jupyter notebooks. We do not go into that situation in this workshop for now. Just know that it is possible by installing a Python installation, Jupyter lab (e.g., via Anaconda) and Quarto ([see Quarto documentation](https://quarto.org/docs/get-started/hello/jupyter.html)).

:::{.callout-note}
Besides R and Python, Quarto can also work with other programming languages, such as Julia or Observable, and it can interact with other software as well, like Neovim and simple Text editors.
:::

## A. Install Quarto and your programming language

::: panel-tabset 

# 1. Quarto in VS Code (R or Python)

## 1. Install Visual Studio Code
Install Visual Studio Code (VS Code) using the [set-up instructions for your operating system](https://code.visualstudio.com/docs/setup/setup-overview).

1. Download VS Code from [https://code.visualstudio.com/](https://code.visualstudio.com/)
2. Walk through the installation steps. The default installation location is usually fine. If you have administrator rights, we recommend to Add VS Code to the PATH if you're using Windows.

## 2. Set up Python and/or R for use in VS Code
1. R: Follow [the instructions here](https://code.visualstudio.com/docs/languages/r#_getting-started) for installing R and using it in VS Code. 
   a. In VS Code, you can open an R terminal to install the `languageserver` package.
2. Python: Follow [the instructions here](https://code.visualstudio.com/docs/python/python-tutorial#_install-a-python-interpreter) for installing a Python interpreter, or see the [installation instructions](https://utrechtuniversity.github.io/workshop-introduction-to-python/installation-and-setup.html#install-python) in our Introduction to Python workshop.
   a. Be sure to also install the Jupyter extension in VS Code if you wish to work with Jupyter notebooks (`.ipynb`).

## 3. Install Quarto
1. Download Quarto from [https://quarto.org/docs/get-started/](https://quarto.org/docs/get-started/)
2. Open the msi/executable file. Answer "Yes" to the pop-up question "Do you want to allow this app to make changes to your device?". Then start the set-up wizard.
3. Choose `Install for all users`. If you do not have administrator rights, select `Install just for you`.
4. Choose the installation location, usually the default proposed location is fine.
5. Installation will start. After installation, click Finish.

## 4. Make VS Code, Quarto and R/Python talk to each other
Now that everything is installed, we need to make sure VS Code can use Quarto and Python/R. 

1. Open VS Code.
2. Open the Extensions view in VS Code (`Ctrl+Shift+X` on Windows and Linux, `Cmd+Shift+X` on macOS)
3. Install the [Quarto extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto) from the Extensions view in VS Code.
4. If you want to use Python in VS Code: 
   a. From the Extensions view in VS Code, install the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python).
   b. Set the Python interpreter: Open the command palette in VS Code (`Ctrl+Shift+P` on Windows and Linux, `Cmd+Shift+P` on macOS), type "Python: Select Interpreter", and select the relevant Python interpreter from the interpreters that VS Code can find.
5. If you want to use R in VS Code: install the [R extension](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r) from the extensions view in VS Code.
6. Check whether Quarto is detected:
   a. Open a new terminal: Terminal > New terminal.
   b. Type `quarto --version`
   c. If a version number appears, Quarto is detected.
7. Check whether Python is detected: 
   a. Open a new terminal or use the one that you used in step 6a.
   b. Type `python --version`
   c. If a version number appears, Python is detected.
8. Check whether R is detected: if you can open an R terminal, it shows you the R version and R is detected successfully.

# 2. Quarto in Rstudio (R)

## 1. Install R and Rstudio

If you do not yet have an installation for R and Rstudio, you need to install them on your device.

- If you have a personal device with administrator/installation rights:
   a. Install R from [https://cran.rstudio.com/](https://cran.rstudio.com/)
   b. Install Rstudio from [https://posit.co/download/rstudio-desktop/#download](https://posit.co/download/rstudio-desktop/#download)

-  If your RStudio version is older than `v2022.07`, then you should update it. Quarto recommends using the latest version of RStudio (currently v.2023.06). 

## 2. Install Quarto and R Markdown

1. In the RStudio console, type `install.packages("rmarkdown")` and `install.packages("quarto")`
2. Load both packages with `library(rmarkdown)` and `library(quarto)`
3. Restart RStudio. 
4. Check whether Quarto is detected: go to the Terminal (next to the Console) and type `quarto --version`. Alternatively, go to `File` > `New project` > `New directory` and check whether the Quarto outputs are presented as options (Quarto project, Quarto website, Quarto blog, Quarto book)
:::
