---
title: "Week 2"
subtitle: "Multilevel Modeling"
date: 2024-02-05
---

## Before class

### Textbook

- {{< fa book >}} McCoach, D. B., & Cintron, D. (2022). Introduction to Modern Modelling Methods (1st edition). SAGE Publications Ltd.

[Chapters 1 and 2](/readings/MLM/MLM_12.pdf)

  - What type of data would necessitate a multilevel analysis? Come up with an example not given in the paper.
  - What are fixed and random effects? How do multilevel models and traditional regression differ in terms of fixed and random effects?
  - How can you statistically determine if your cases are not independent?
  - What assumptions does MLM have?
  - What is the difference between grand-mean and group mean centered data?
  - What is the folly of trying to account for dependence by including level 2 data in an ordinary regression model?

## After class

### Textbook 

- {{< fa book >}} Xing Liu (2023). Categorical Data Analysis and Multilevel Modeling Using R (1st edition). SAGE Publications Ltd.

    - [Ch.10](/readings/MLM/mlm_inr.pdf)

### Podcasts

{{< fa web >}} S5E05 Multilevel Models Unleashed – QuantitudePod. (n.d.). Retrieved January 3, 2024, from https://quantitudepod.org/s5e05-multilevel-models/

