---
title: "Week 6"
subtitle: "Multinomial Regression"
date: 2023-02-27
---
## Before Class

### Articles

- {{< fa book >}} https://bookdown.org/chua/ber642_advanced_regression/multinomial-logistic-regression.html#introduction-to-multinomial-logistic-regression

- {{< fa book >}} McNulty, K. (2021). Handbook of Regression Modeling in People Analytics: With Examples in R and Python. [Multinomial Regression](https://peopleanalytics-regression-book.org/multinomial-logistic-regression-for-nominal-category-outcomes.html). 

  - Describe the difference between a stratified versus a multinomial approach to modeling an outcome with more than two nominal categories.
  
  - Describe how you would interpret the odds ratio of an input variable for a given category in a stratified modeling approach.
  
  - Describe what is meant by the ‘reference’ of a multinomial logistic regression model with at least three nominal outcome categories.
  
  - Describe how you would interpret the odds ratio of an input variable for a given category in a multinomial modeling approach.
  
  - Given a multinomial logistic regression model with outcome categories A, B, C and D and reference category A, describe two ways to determine the coefficients of a multinomial logistic regression model with reference category C.
  
  - Describe a process for safely simplifying a multinomial logistic regression model by removing input variables.



