---
title: "Week 8"
subtitle: "Poission Regression"
date: 2023-03-18
---

## Before class
    
### Articles

- {{< fa book >}}Coxe, S., West, S. G., & Aiken, L. S. (2009). [The Analysis of Count Data: A Gentle Introduction to Poisson Regression and Its Alternatives](/readings/count_data_poisson.pdf). Journal of Personality Assessment, 91(2), 121–136. https://doi.org/10.1080/00223890802634175

- {{< fa book >}} Ryan, W. H., Evers, E. R. K., & Moore, D. A. (2021). [Poisson Regressions: A Little Fishy](/readings/collabra_2021_fishy.pdf). Collabra: Psychology, 7(1), 27242. https://doi.org/10.1525/collabra.27242

#### Questions

  - How does the Poisson distribution differ from other distributions, such as the normal distribution?
  
  - How do we interpret the parameters of the poisson?
  
  - What are the assumptions of Poisson regression?
  
  - What is overdispersion?
    
  - How is poisson related to the negative binomial and zero-inflated?
  
  - What are some of the issues associted with Poisson regression?
  
## After class

- Class video: 

{{< video https://www.youtube.com/watch?v=_VTuGSWOWyc width="800" height="400" >}}

### Textbook

- {{< fa book >}} Xing Liu (2023). Categorical Data Analysis and Multilevel Modeling Using R (1st edition). SAGE Publications Ltd.

    - [Ch.8](/readings/poi/poi.pdf)
    - [Ch.9](/readings/poi/negbinom.pdf)
