---
title: "Assignments"
---
## Preparation

You will get the most out of this seminar if you (1) attend regularly, (2) engage with the readings, and (3) write thoughtfully.

To help you do all this successfully, there are three assignments for this course: 

- **Mini presentation and discussion leading**: Once during the semester, you will be responsible for preparing a presentation and leading the discussion for a class session. During the first day of class, I will provide a spreadsheet where you will select the week you want to be responsible for. [**Complete instructions and details for this assignment are here.**](/Assignments/presentation-discussion.qmd)

- **Labs**: 
Each week (Wednesday) we will have one corresponding lab exercise that will be started in class. The purpose is for you to get direct experience conducting the analyses that you learn. Each lab exercise will consist of several questions and will require R (will also accept Python) to answer the questions in a reproducible manner. All lab assignments must be reproducible (i.e., I can replicate the work you did without any errors). You may complete the labs by yourself or working with another person. If you work with another person, your work must obviously be your own.

Ideally, you will finish labs in class. However, if you do not complete it in class, you can turn them in on Friday (due at 11:00 P.M.) Please let me know if you need an extension.

- **Tutorial**: 
For your final project, you will create a tutorial explaining how to run a particular analysis in R. This will involve finding data or using your own data. The final project gives you a chance to pursue a specific method discussed in class and apply it to your own data.[**Complete instructions and details for this assignment are here.**](/Assignments/blog.qmd)

## Exams

There are no exams! Read a bunch of things, write some things, participate in class. That's it.
